'use client'
import {useEffect,useState} from 'react'
import {supabase} from '@/lib/supabase'
import type {Banner,Character,LinkItem,Prompt,SiteSettings,Pair,PairLog} from '@/lib/types'
import BgmPlayer from '@/components/BgmPlayer'

const fallback:SiteSettings={title:'YEONU',subtitle:'personal archive',profileName:'여누',profileImage:'',about:'안녕하세요, 여누입니다.\n\n주로 짤뽑, 프롬 공유, 교류를 하고 있으며,\n주로 비계에서 지냈어서 아직 앵챗계가 익숙하지 않기에 틧이 적고 답멘이 느릴 수 있습니다.\n트친 한 분, 한 분 어떻게든 교류하려고 하고 있지만 내향적인 성격이라 그러지 못 할 때도 있습니다.',love:[],hate:[],bgmUrl:'',bgmAutoplay:true,bgmLoop:true}
export default function Home(){
 const db=supabase(); const [settings,setSettings]=useState(fallback); const [characters,setCharacters]=useState<Character[]>([]); const [prompts,setPrompts]=useState<Prompt[]>([]); const [links,setLinks]=useState<LinkItem[]>([]); const [moving,setMoving]=useState<Banner[]>([]); const [friends,setFriends]=useState<Banner[]>([]); const [pairs,setPairs]=useState<Pair[]>([]); const [pairLogs,setPairLogs]=useState<PairLog[]>([]); const [selected,setSelected]=useState<Character|null>(null); const [copied,setCopied]=useState<string|null>(null); const [isAdmin,setIsAdmin]=useState(false)
 useEffect(()=>{(async()=>{ const [s,c,p,l,m,f,prs,logs,u]=await Promise.all([db.from('site_settings').select('*').single(),db.from('characters').select('*').order('sort_order'),db.from('prompts').select('*').order('sort_order'),db.from('links').select('*').order('sort_order'),db.from('moving_banners').select('*').order('sort_order'),db.from('friend_banners').select('*').order('sort_order'),db.from('pairs').select('*').order('sort_order'),db.from('pair_logs').select('*').order('sort_order'),db.auth.getUser()]); if(s.data?.data)setSettings({...fallback,...s.data.data}); setCharacters(c.data||[]);setPrompts(p.data||[]);setLinks(l.data||[]);setMoving(m.data||[]);setFriends(f.data||[]);setPairs(prs.data||[]);setPairLogs(logs.data||[]); if(u.data.user){const q=await db.from('profiles').select('role').eq('id',u.data.user.id).single();setIsAdmin(q.data?.role==='admin')}})()},[])
 const copy=async(id:string,text:string)=>{await navigator.clipboard.writeText(text);setCopied(id);setTimeout(()=>setCopied(null),1300)}
 return <div className="shell"><aside className="side"><div className="brand">{settings.title}<small>{settings.subtitle}</small></div><nav className="nav"><a href="#profile">PROFILE</a><a href="#characters">CHARACTERS</a><a href="#prompts">PROMPTS</a><a href="#pairs">PAIRS</a><a href="#links">LINKS</a><a href="#friends">FRIENDS</a></nav><div style={{marginTop:'auto',paddingTop:30,fontSize:11,color:'var(--muted)'}}>archive · 2026</div></aside>
 <main className="main">
   <BgmPlayer src={settings.bgmUrl} autoplay={settings.bgmAutoplay} loop={settings.bgmLoop}/>
   <section className="ticker">{moving.length?<div className="track">{[...moving,...moving].map((b,i)=><a key={b.id+'-'+i} href={b.link_url||undefined} target={b.link_url?'_blank':undefined} rel="noreferrer">{b.image_url?<img src={b.image_url} alt={b.alt}/>:<div className="placeholder">IMAGE</div>}</a>)}</div>:<div style={{padding:'28px',textAlign:'center',color:'var(--muted)',fontSize:12}}>MOVING IMAGE BANNER · admin에서 이미지와 링크를 추가하세요</div>}</section>
   <section id="profile" className="hero"><div className="card"><div className="profile"><div className="avatar">{settings.profileImage?<img src={settings.profileImage} alt="profile"/>:<div style={{height:'100%',display:'grid',placeItems:'center',color:'var(--muted)',fontSize:12}}>PROFILE</div>}</div><div><div className="eyebrow">ABOUT ME</div><h1>{settings.profileName}</h1><p>{settings.about}</p></div></div></div><div className="card"><div className="eyebrow">LOVE / HATE</div><h2>things I like</h2><div className="chips">{settings.love.map((x,i)=><span className="chip" key={'l'+i}>♡ {x}</span>)}</div><h2 style={{marginTop:24}}>things I avoid</h2><div className="chips">{settings.hate.map((x,i)=><span className="chip" key={'h'+i}>× {x}</span>)}</div></div></section>
   <section id="characters" className="section"><div className="section-head"><div><div className="eyebrow">CHARACTERS</div><h2>my characters</h2></div></div><div className="grid">{characters.map(c=><article className="character" key={c.id} onClick={()=>setSelected(c)}>{c.image_url?<img src={c.image_url} alt={c.name}/>:<div style={{height:'100%',display:'grid',placeItems:'center',color:'var(--muted)'}}>NO IMAGE</div>}<div className="name">{c.name}</div></article>)}</div></section>
   <section id="pairs" className="section"><div className="eyebrow">PAIRS</div><h2>relationships</h2><div className="pairgrid">{pairs.map(pr=><article className="paircard" key={pr.id} onClick={()=>{const target=document.getElementById(`pair-${pr.id}`);target?.scrollIntoView({behavior:'smooth',block:'center'})}}>{pr.image_url?<img src={pr.image_url} alt={pr.name}/>:<div className="pairplaceholder">PAIR</div>}<div className="pairoverlay"><b>{pr.name}</b><small>{charDisplay(pr,characters)}</small></div></article>)}</div><div className="pairdetails">{pairs.map(pr=>{const logs=pairLogs.filter(x=>x.pair_id===pr.id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));return <article id={`pair-${pr.id}`} className="card pairdetail" key={pr.id}><div className="section-head"><div><div className="eyebrow">PAIR</div><h2>{pr.name}</h2><div className="pairchars">{charDisplay(pr,characters)}</div></div><div className="chips">{(pr.tags||[]).map((t,i)=><span className="chip" key={i}>#{t}</span>)}</div></div>{pr.image_url&&<img className="pairhero" src={pr.image_url} alt={pr.name}/>}<p>{pr.description}</p><div className="logs"><div className="eyebrow">LOG ARCHIVE</div>{logs.length?logs.map(lg=><details className="logitem" key={lg.id}><summary><b>{lg.title||'UNTITLED LOG'}</b>{lg.log_date&&<small>{lg.log_date}</small>}</summary><div className="logbody">{lg.body}</div></details>):<div className="emptylog">아직 백업된 로그가 없습니다.</div>}</div></article>})}</div></section>
   <section id="prompts" className="section"><div className="eyebrow">PROMPTS</div><h2>prompt archive</h2><div className="adminlist">{prompts.map(p=><article className="card prompt" key={p.id}><div className="top"><div><b>{p.title}</b><div className="chips" style={{marginTop:7}}><span className="chip">{p.category||'etc'}</span>{p.tags?.map((t,i)=><span className="chip" key={i}>#{t}</span>)}</div></div><button className="btn" onClick={()=>copy(p.id,p.body)}>{copied===p.id?'COPIED!':'COPY'}</button></div><code>{p.body}</code></article>)}</div></section>
   <section id="links" className="section"><div className="eyebrow">LINKS</div><h2>elsewhere</h2><div className="links">{links.map(l=><a className="linkrow" key={l.id} href={l.url} target="_blank" rel="noreferrer"><span><b>{l.title}</b><br/><small style={{color:'var(--muted)'}}>{l.description}</small></span><span>↗</span></a>)}</div></section>
   <section id="friends" className="section"><div className="eyebrow">FRIENDS</div><h2>friend banners</h2><div className="friendgrid">{friends.map(b=><a key={b.id} href={b.link_url||undefined} target={b.link_url?'_blank':undefined} rel="noreferrer">{b.image_url&&<img src={b.image_url} alt={b.alt}/>}</a>)}</div></section>
   <footer className="footer">YEONU · personal archive</footer>
   {selected&&<div className="modal" onClick={()=>setSelected(null)}><div className="modalbox" onClick={e=>e.stopPropagation()}><div className="row" style={{justifyContent:'space-between',alignItems:'center'}}><div><div className="eyebrow">CHARACTER</div><h2>{selected.name}</h2></div><button className="btn" onClick={()=>setSelected(null)}>CLOSE</button></div>{selected.image_url&&<img src={selected.image_url} alt={selected.name} style={{width:'100%',maxHeight:400,objectFit:'contain',borderRadius:18,background:'var(--blue2)'}}/>}<p>{selected.summary}</p><p>{selected.details}</p></div></div>}
   {isAdmin&&<div className="adminbar"><a className="btn" href="/admin">ADMIN ↗</a></div>}
 </main></div>
}

function charDisplay(pr:Pair, chars:Character[]){ const a=chars.find(c=>c.id===pr.character_one_id)?.name || ''; const b=chars.find(c=>c.id===pr.character_two_id)?.name || ''; return [a,b].filter(Boolean).join(' × ') || 'PAIR'; }
